services:
  postgres:
    ports:
      - "5432:5432"

  backend:
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend

  frontend:
    ports:
      - "8050:8050"
    volumes:
      - ./frontend:/app/frontend
