services:
  postgres:
    restart: always

  backend:
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

  frontend:
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
