apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-config
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: ccs
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  LOG_LEVEL: {{ .Values.logLevel | quote }}
