apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-db-secret
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: ccs
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
type: Opaque
stringData:
  DB_HOST: {{ .Values.database.host }}
  DB_PORT: {{ .Values.database.port | quote }}
  DB_USER: {{ .Values.database.username }}
  DB_PASSWORD: {{ .Values.database.password }}
  DB_NAME: {{ .Values.database.name }}