apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: ccs
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
